external-dns:

  extraArgs:
  # set cache to reduce rate-limit problems on ionos
  - --provider-cache-time=15m

  provider:
    name: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-key
          key: apiKey
  
  
  
  
